export default [
  {
    path: '/',
    component: '../layouts/baseLayout',
    routes: [
      {path: '/', component: './Home/index', title: '首页'},
      {path: '/my', component: './My/index', title: '我的'},
      {path: '/home', component: './Home/index', title: '首页'},
      {path: '/login', component: './login/index', title: '登录'},
      //   { path: '/news', component: './News/index', title: '消息' },
      //   { path: '/order', component: './Order/index', title: '我的订单' },
      //   { path: '/goodsSearch', component: './GoodsSearch/index', title: '商品搜索' },
      //   { path: '/contact', component: './Contact/index', title: '联系总部' },
      //   { path: '/introduction', component: './Introduction/index', title: '企业介绍' },
      //   { path: '/userInfo', component: './UserInfo/index', title: '个人信息' },
      //   { path: '/setting', component: './Setting/index', title: '设置' },
      //   { path: '/changePwd', component: './ChangePwd/index', title: '修改密码' },
      //   { path: '/forgetPwd', component: './ForgetPwd/index', title: '忘记密码' },
      //   { path: '/address', component: './Address/index', title: '收货地址' },
      //   { path: '/editAddress', component: './EditAddress/index', title: '新增地址' },
      //   { path: '/businessNews', component: './BusinessNews/index', title: '业务消息' },
      //   { path: '/returnList', component: './ReturnList/index', title: '退货查询' },
      //   { path: '/returnOrderSearch', component: './ReturnOrderSearch/index', title: '退货查询' },
      //   { path: '/orderSearch', component: './OrderSearch/index', title: '订单搜索' },
      //   { path: '/shopCar', component: './ShopCar/index', title: '购物车' },
      //   { path: '/payResult', component: './PayResult/index', title: '支付结果' },
      //   { path: '/orderPay', component: './OrderPay/index', title: '收银台' },
      //   { path: '/orderConfirm', component: './OrderConfirm/index', title: '确认订单' },
      //   { path: '/productList', component: './ProductList/index', title: '商品清单' },
      //   { path: '/returnProductList', component: './ReturnProductList/index', title: '商品清单' },
      //   { path: '/goodsDetail', component: './GoodsDetail/index', title: '商品详情' },
      //   { path: '/orderDetail', component: './OrderDetail/index', title: '订单详情' },
      //   { path: '/paymentRecord', component: './PaymentRecord/index', title: '付款记录' },
      //   { path: '/confirmReceive', component: './ConfirmReceive/index', title: '商品收货清单' },
      //   { path: '/returnApply', component: './ReturnApply/index', title: '退货申请' },
      //   { path: '/returnSelect', component: './ReturnSelect/index', title: '退货申请' },
      //   { path: '/returnDetail', component: './ReturnDetail/index', title: '退单详情' },
      //   { path: '/newsDetail', component: './NewsDetail/index', title: '消息详情' },
      //   { path: '/favouriteList', component: './FavouriteList/index', title: '常购清单' },
      //   { path: '/login', component: './Login/index', title: '登录' },
      //   { path: '/privacy', component: './Privacy/index', title: '隐私政策' },
      {
        path: '/exception',
        component: '../layouts/ExceptionLayout',
        routes: [
          {path: '/exception/403', title: '无权限', component: './exception/403'},
          {path: '/exception/500', title: '服务器出错了', component: './exception/500'},
        ],
      },
      {component: '404', title: '页面没找到'},
    ],
  },
];
